name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"  # Fixed cron syntax to run every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:  # Correct indentation
          github_user_name: sameekshaagupta
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push the generated snake grid to GitHub Pages
      - name: Deploy Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Correct reference
